"""Added age and recipe_ids records to the User model.

Revision ID: 17041a436dcf
Revises: e898b7f69b4b
Create Date: 2025-11-30 19:10:31.948896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17041a436dcf'
down_revision: Union[str, Sequence[str], None] = 'e898b7f69b4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('recipe_ids', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'recipe_ids')
    op.drop_column('users', 'age')
    # ### end Alembic commands ###
