"""Added user role and sex record to User model.

Revision ID: 7597cfd3a685
Revises: dab77d38ae58
Create Date: 2025-11-26 20:08:24.408238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7597cfd3a685'
down_revision: Union[str, Sequence[str], None] = 'dab77d38ae58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=50), nullable=True))
    op.add_column('users', sa.Column('sex', sa.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sex')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
