# backend/recipe-service/src/init_recipes.py
"""
Initialize MongoDB with 55+ real recipes that reference ingredients
by deterministic UUID (same namespace as init_ingredients.py).

Run init_ingredients.py FIRST, then run this script.

Run from the src/ directory:
    python init_recipes.py
"""

import asyncio
import sys
import uuid
import random
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from db.mongodb import connect_to_mongodb, disconnect_from_mongodb, get_database
from core.config import settings
from models.model import Recipe, WeightedIngredient

# ---------------------------------------------------------------------------
# Deterministic ID generation — MUST match init_ingredients.py
# ---------------------------------------------------------------------------
INGREDIENT_NS = uuid.UUID("a3bb189e-8bf9-3888-9912-ace4e6543002")


def make_ingredient_id(name: str) -> str:
    """Generate a deterministic UUID-5 from an ingredient name."""
    return str(uuid.uuid5(INGREDIENT_NS, name.lower().strip()))


def ing(name: str, capacity: str, quantity: float) -> dict:
    """Shorthand helper to build a WeightedIngredient dict."""
    return {
        "ingredient_id": make_ingredient_id(name),
        "capacity": capacity,
        "quantity": quantity,
    }


# ---------------------------------------------------------------------------
# Fake author IDs (simulating seeded users)
# ---------------------------------------------------------------------------
AUTHORS = [
    "system-seed|chef-anna",
    "system-seed|chef-marco",
    "system-seed|chef-yuki",
    "system-seed|chef-priya",
    "system-seed|chef-carlos",
]

# ---------------------------------------------------------------------------
# Recipe data
# ---------------------------------------------------------------------------
RECIPES = [
    # ==================== BREAKFAST ====================
    {
        "name": "Classic Scrambled Eggs",
        "author_id": AUTHORS[0],
        "ingredients": [
            ing("Egg", "pcs", 4),
            ing("Butter", "g", 20),
            ing("Whole Milk", "ml", 30),
            ing("Salt", "g", 2),
            ing("Black Pepper", "g", 1),
            ing("Chives Fresh", "g", 5),
        ],
        "prepare_instruction": [
            "Crack eggs into a bowl and add milk. Whisk vigorously until smooth and slightly frothy.",
            "Melt butter in a non-stick pan over medium-low heat.",
            "Pour in the egg mixture. Let it sit for 20 seconds until edges start to set.",
            "Gently push eggs from the edges toward the center with a spatula, creating soft curds.",
            "Continue folding gently until eggs are just set but still glossy and moist.",
            "Remove from heat, season with salt and pepper, and garnish with chopped chives.",
        ],
        "time_to_prepare": 600,
        "total_likes": 87,
    },
    {
        "name": "Avocado Toast with Poached Egg",
        "author_id": AUTHORS[0],
        "ingredients": [
            ing("Sourdough Bread", "g", 100),
            ing("Avocado", "g", 150),
            ing("Egg", "pcs", 2),
            ing("Lemon Juice", "ml", 10),
            ing("Chili Flakes", "g", 1),
            ing("Salt", "g", 2),
            ing("Black Pepper", "g", 1),
            ing("Extra Virgin Olive Oil", "ml", 5),
        ],
        "prepare_instruction": [
            "Toast the sourdough bread slices until golden and crispy.",
            "Halve the avocado, remove the pit, and scoop the flesh into a bowl.",
            "Mash the avocado with a fork, add lemon juice, salt, and pepper. Mix well.",
            "Bring a pot of water to a gentle simmer. Create a small whirlpool and crack each egg into the center.",
            "Poach eggs for 3-4 minutes until whites are set but yolks are still runny.",
            "Spread mashed avocado generously on each toast slice.",
            "Place a poached egg on top, drizzle with olive oil, and sprinkle with chili flakes.",
        ],
        "time_to_prepare": 900,
        "total_likes": 142,
    },
    {
        "name": "Banana Oat Pancakes",
        "author_id": AUTHORS[1],
        "ingredients": [
            ing("Banana", "g", 200),
            ing("Oats", "g", 100),
            ing("Egg", "pcs", 2),
            ing("Whole Milk", "ml", 60),
            ing("Baking Powder", "g", 5),
            ing("Cinnamon", "g", 2),
            ing("Vanilla Extract", "ml", 5),
            ing("Butter", "g", 15),
            ing("Maple Syrup", "ml", 30),
        ],
        "prepare_instruction": [
            "Blend oats in a food processor until they form a fine flour.",
            "Mash bananas in a large bowl until smooth.",
            "Add eggs, milk, vanilla extract, and cinnamon to the mashed bananas. Mix well.",
            "Fold in the oat flour and baking powder until just combined. Do not overmix.",
            "Heat a non-stick pan over medium heat and melt a little butter.",
            "Pour about 60ml of batter per pancake. Cook until bubbles form on the surface, about 2-3 minutes.",
            "Flip and cook for another 1-2 minutes until golden brown.",
            "Serve stacked with maple syrup drizzled on top.",
        ],
        "time_to_prepare": 1200,
        "total_likes": 203,
    },
    {
        "name": "Greek Yogurt Parfait",
        "author_id": AUTHORS[2],
        "ingredients": [
            ing("Greek Yogurt", "g", 250),
            ing("Granola", "g", 60),
            ing("Blueberry", "g", 80),
            ing("Strawberry", "g", 80),
            ing("Honey", "g", 20),
            ing("Chia Seeds", "g", 10),
            ing("Almonds", "g", 20),
        ],
        "prepare_instruction": [
            "Wash and slice the strawberries. Rinse the blueberries.",
            "In a tall glass or bowl, layer a third of the Greek yogurt on the bottom.",
            "Add a layer of granola, then a layer of mixed berries.",
            "Repeat the layers two more times, ending with berries on top.",
            "Drizzle with honey, sprinkle chia seeds and sliced almonds.",
            "Serve immediately or refrigerate for up to 2 hours.",
        ],
        "time_to_prepare": 300,
        "total_likes": 178,
    },
    {
        "name": "French Toast",
        "author_id": AUTHORS[0],
        "ingredients": [
            ing("White Bread", "g", 200),
            ing("Egg", "pcs", 3),
            ing("Whole Milk", "ml", 80),
            ing("Cinnamon", "g", 3),
            ing("Vanilla Extract", "ml", 5),
            ing("Butter", "g", 30),
            ing("Powdered Sugar", "g", 15),
            ing("Maple Syrup", "ml", 30),
        ],
        "prepare_instruction": [
            "In a wide shallow bowl, whisk together eggs, milk, cinnamon, and vanilla extract.",
            "Heat a large skillet or griddle over medium heat and melt half the butter.",
            "Dip each bread slice into the egg mixture, letting it soak for 5 seconds per side.",
            "Place soaked bread in the skillet. Cook for 2-3 minutes until golden brown.",
            "Flip and cook the other side for another 2-3 minutes.",
            "Transfer to a plate, dust with powdered sugar, and serve with maple syrup.",
        ],
        "time_to_prepare": 900,
        "total_likes": 156,
    },
    {
        "name": "Spinach and Mushroom Omelette",
        "author_id": AUTHORS[3],
        "ingredients": [
            ing("Egg", "pcs", 3),
            ing("Spinach", "g", 60),
            ing("White Mushroom", "g", 80),
            ing("Cheddar Cheese", "g", 40),
            ing("Butter", "g", 15),
            ing("Salt", "g", 2),
            ing("Black Pepper", "g", 1),
        ],
        "prepare_instruction": [
            "Wash spinach and slice mushrooms thinly.",
            "Melt half the butter in a non-stick pan over medium heat. Sauté mushrooms for 3-4 minutes until golden.",
            "Add spinach and cook for 1 minute until wilted. Remove vegetables and set aside.",
            "Whisk eggs with salt and pepper in a bowl.",
            "Melt remaining butter in the same pan. Pour in eggs and tilt to spread evenly.",
            "When the bottom is set but top is still slightly wet, add sautéed vegetables and grated cheese to one half.",
            "Fold the omelette over, cook for another 30 seconds, and slide onto a plate.",
        ],
        "time_to_prepare": 600,
        "total_likes": 94,
    },
    {
        "name": "Overnight Oats with Berries",
        "author_id": AUTHORS[2],
        "ingredients": [
            ing("Oats", "g", 80),
            ing("Whole Milk", "ml", 200),
            ing("Greek Yogurt", "g", 60),
            ing("Chia Seeds", "g", 15),
            ing("Honey", "g", 20),
            ing("Blueberry", "g", 50),
            ing("Raspberry", "g", 50),
            ing("Vanilla Extract", "ml", 3),
        ],
        "prepare_instruction": [
            "In a mason jar or container, combine oats, milk, yogurt, chia seeds, honey, and vanilla extract.",
            "Stir well to combine all ingredients thoroughly.",
            "Cover and refrigerate for at least 6 hours or overnight.",
            "In the morning, stir the oats and add a splash of milk if too thick.",
            "Top with fresh blueberries and raspberries.",
            "Enjoy cold straight from the fridge.",
        ],
        "time_to_prepare": 300,
        "total_likes": 215,
    },
    {
        "name": "Shakshuka",
        "author_id": AUTHORS[3],
        "ingredients": [
            ing("Egg", "pcs", 4),
            ing("Canned Tomatoes", "g", 400),
            ing("Onion", "g", 100),
            ing("Bell Pepper Red", "g", 100),
            ing("Garlic", "g", 10),
            ing("Cumin", "g", 3),
            ing("Paprika", "g", 3),
            ing("Cayenne Pepper", "g", 1),
            ing("Olive Oil", "ml", 20),
            ing("Salt", "g", 3),
            ing("Cilantro Fresh", "g", 10),
            ing("Feta Cheese", "g", 40),
        ],
        "prepare_instruction": [
            "Dice the onion and bell pepper. Mince the garlic.",
            "Heat olive oil in a large skillet over medium heat. Sauté onion and pepper for 5 minutes.",
            "Add garlic, cumin, paprika, and cayenne pepper. Cook for 1 minute until fragrant.",
            "Pour in canned tomatoes, break them up, and simmer for 10 minutes until sauce thickens.",
            "Make 4 wells in the sauce and crack an egg into each well.",
            "Cover and cook for 5-7 minutes until egg whites are set but yolks are still runny.",
            "Crumble feta cheese on top and garnish with fresh cilantro.",
            "Serve directly from the skillet with crusty bread.",
        ],
        "time_to_prepare": 1500,
        "total_likes": 267,
    },
    {
        "name": "Smoothie Bowl",
        "author_id": AUTHORS[2],
        "ingredients": [
            ing("Banana", "g", 200),
            ing("Blueberry", "g", 100),
            ing("Greek Yogurt", "g", 100),
            ing("Honey", "g", 15),
            ing("Granola", "g", 40),
            ing("Coconut Meat", "g", 20),
            ing("Chia Seeds", "g", 10),
            ing("Strawberry", "g", 50),
        ],
        "prepare_instruction": [
            "Freeze bananas and blueberries for at least 2 hours.",
            "Blend frozen fruit with Greek yogurt and honey until thick and creamy.",
            "Pour into a bowl — the consistency should be thicker than a smoothie.",
            "Top with granola, sliced strawberries, shredded coconut, and chia seeds.",
            "Serve immediately before it melts.",
        ],
        "time_to_prepare": 600,
        "total_likes": 189,
    },

    # ==================== SOUPS ====================
    {
        "name": "Classic Tomato Soup",
        "author_id": AUTHORS[1],
        "ingredients": [
            ing("Canned Tomatoes", "g", 800),
            ing("Onion", "g", 150),
            ing("Garlic", "g", 15),
            ing("Carrot", "g", 100),
            ing("Celery", "g", 60),
            ing("Olive Oil", "ml", 30),
            ing("Vegetable Broth", "ml", 500),
            ing("Basil Fresh", "g", 15),
            ing("Heavy Cream", "ml", 60),
            ing("Salt", "g", 5),
            ing("Black Pepper", "g", 2),
            ing("White Sugar", "g", 5),
        ],
        "prepare_instruction": [
            "Dice onion, carrot, and celery. Mince the garlic.",
            "Heat olive oil in a large pot over medium heat. Sauté onion, carrot, and celery for 5-7 minutes.",
            "Add garlic and cook for 1 minute until fragrant.",
            "Add canned tomatoes and vegetable broth. Bring to a boil.",
            "Reduce heat and simmer for 20 minutes until vegetables are tender.",
            "Add fresh basil and sugar. Blend with an immersion blender until smooth.",
            "Stir in heavy cream, season with salt and pepper.",
            "Serve hot with a swirl of cream and extra basil leaves.",
        ],
        "time_to_prepare": 2400,
        "total_likes": 312,
    },
    {
        "name": "Chicken Noodle Soup",
        "author_id": AUTHORS[0],
        "ingredients": [
            ing("Chicken Breast", "g", 300),
            ing("Egg Noodles", "g", 150),
            ing("Carrot", "g", 120),
            ing("Celery", "g", 80),
            ing("Onion", "g", 100),
            ing("Garlic", "g", 10),
            ing("Chicken Broth", "ml", 1500),
            ing("Bay Leaves", "g", 2),
            ing("Thyme Dried", "g", 2),
            ing("Parsley Fresh", "g", 15),
            ing("Salt", "g", 5),
            ing("Black Pepper", "g", 2),
            ing("Olive Oil", "ml", 15),
        ],
        "prepare_instruction": [
            "Dice onion, carrot, and celery into small uniform pieces. Mince the garlic.",
            "Heat olive oil in a large pot. Add chicken breasts and brown on both sides for 3 minutes each. Remove and set aside.",
            "Sauté onion, carrot, and celery in the same pot for 5 minutes.",
            "Add garlic and cook for 30 seconds. Pour in chicken broth, add bay leaves and thyme.",
            "Return chicken to the pot. Bring to a boil, then reduce heat and simmer for 15 minutes.",
            "Remove chicken, shred with two forks, and return to the pot.",
            "Add egg noodles and cook for 8 minutes until tender.",
            "Remove bay leaves, season with salt and pepper, and garnish with fresh parsley.",
        ],
        "time_to_prepare": 2700,
        "total_likes": 289,
    },
    {
        "name": "Minestrone Soup",
        "author_id": AUTHORS[1],
        "ingredients": [
            ing("Onion", "g", 100),
            ing("Carrot", "g", 100),
            ing("Celery", "g", 60),
            ing("Zucchini", "g", 120),
            ing("Green Beans", "g", 80),
            ing("Canned Tomatoes", "g", 400),
            ing("Kidney Beans", "g", 200),
            ing("Penne", "g", 80),
            ing("Vegetable Broth", "ml", 1000),
            ing("Garlic", "g", 10),
            ing("Olive Oil", "ml", 30),
            ing("Parmesan Cheese", "g", 30),
            ing("Basil Fresh", "g", 10),
            ing("Salt", "g", 5),
            ing("Black Pepper", "g", 2),
        ],
        "prepare_instruction": [
            "Dice onion, carrot, celery, and zucchini. Trim and cut green beans into 2 cm pieces.",
            "Heat olive oil in a large pot. Sauté onion, carrot, and celery for 5 minutes.",
            "Add garlic and cook for 1 minute.",
            "Add canned tomatoes, vegetable broth, and green beans. Bring to a boil.",
            "Reduce heat and simmer for 15 minutes.",
            "Add zucchini, kidney beans, and pasta. Cook for another 10 minutes until pasta is al dente.",
            "Season with salt and pepper.",
            "Serve topped with grated Parmesan and fresh basil.",
        ],
        "time_to_prepare": 2400,
        "total_likes": 198,
    },
    {
        "name": "Thai Coconut Soup (Tom Kha Gai)",
        "author_id": AUTHORS[2],
        "ingredients": [
            ing("Chicken Breast", "g", 250),
            ing("Coconut Milk", "ml", 400),
            ing("Chicken Broth", "ml", 400),
            ing("White Mushroom", "g", 150),
            ing("Lemongrass", "g", 20),
            ing("Ginger", "g", 20),
            ing("Lime Juice", "ml", 30),
            ing("Fish Sauce", "ml", 20),
            ing("Chili Pepper", "g", 10),
            ing("Cilantro Fresh", "g", 15),
            ing("Green Onion", "g", 20),
            ing("Brown Sugar", "g", 10),
        ],
        "prepare_instruction": [
            "Slice chicken breast into thin strips. Quarter the mushrooms.",
            "Bruise lemongrass stalks with the back of a knife and cut into 5 cm pieces. Slice ginger thinly.",
            "In a pot, bring chicken broth to a boil. Add lemongrass and ginger slices. Simmer for 5 minutes.",
            "Add coconut milk and bring back to a gentle simmer.",
            "Add chicken strips and mushrooms. Cook for 8-10 minutes until chicken is cooked through.",
            "Remove from heat. Stir in lime juice, fish sauce, and brown sugar.",
            "Remove lemongrass pieces.",
            "Serve garnished with sliced chili, cilantro, and green onion.",
        ],
        "time_to_prepare": 1800,
        "total_likes": 234,
    },
    {
        "name": "Lentil Soup",
        "author_id": AUTHORS[3],
        "ingredients": [
            ing("Red Lentils", "g", 250),
            ing("Onion", "g", 120),
            ing("Carrot", "g", 100),
            ing("Celery", "g", 60),
            ing("Garlic", "g", 15),
            ing("Tomato Paste", "g", 30),
            ing("Cumin", "g", 5),
            ing("Turmeric", "g", 2),
            ing("Vegetable Broth", "ml", 1200),
            ing("Olive Oil", "ml", 25),
            ing("Lemon Juice", "ml", 20),
            ing("Salt", "g", 5),
            ing("Black Pepper", "g", 2),
            ing("Parsley Fresh", "g", 10),
        ],
        "prepare_instruction": [
            "Rinse red lentils under cold water until the water runs clear.",
            "Dice onion, carrot, and celery. Mince the garlic.",
            "Heat olive oil in a large pot over medium heat. Sauté onion, carrot, and celery for 5 minutes.",
            "Add garlic, cumin, and turmeric. Cook for 1 minute until fragrant.",
            "Stir in tomato paste and cook for another minute.",
            "Add lentils and vegetable broth. Bring to a boil.",
            "Reduce heat and simmer for 20-25 minutes until lentils are completely tender.",
            "Blend half the soup for a creamy texture while keeping some chunks.",
            "Stir in lemon juice, season with salt and pepper, and garnish with parsley.",
        ],
        "time_to_prepare": 2400,
        "total_likes": 276,
    },
    {
        "name": "Broccoli Cheddar Soup",
        "author_id": AUTHORS[0],
        "ingredients": [
            ing("Broccoli", "g", 500),
            ing("Cheddar Cheese", "g", 200),
            ing("Onion", "g", 100),
            ing("Garlic", "g", 10),
            ing("Butter", "g", 40),
            ing("All-Purpose Flour", "g", 30),
            ing("Chicken Broth", "ml", 700),
            ing("Heavy Cream", "ml", 120),
            ing("Nutmeg", "g", 1),
            ing("Salt", "g", 5),
            ing("Black Pepper", "g", 2),
        ],
        "prepare_instruction": [
            "Cut broccoli into small florets. Dice the onion and mince the garlic.",
            "Melt butter in a large pot over medium heat. Sauté onion for 3 minutes, then add garlic.",
            "Sprinkle flour over the onion mixture and stir constantly for 2 minutes to form a roux.",
            "Gradually whisk in chicken broth, ensuring no lumps form.",
            "Bring to a boil, then add broccoli florets. Simmer for 15 minutes until broccoli is tender.",
            "Blend about two-thirds of the soup until smooth, leaving some broccoli pieces for texture.",
            "Stir in heavy cream and grated cheddar cheese until melted and smooth.",
            "Season with nutmeg, salt, and pepper. Serve hot.",
        ],
        "time_to_prepare": 2100,
        "total_likes": 243,
    },
    {
        "name": "Mushroom Cream Soup",
        "author_id": AUTHORS[1],
        "ingredients": [
            ing("Cremini Mushroom", "g", 400),
            ing("White Mushroom", "g", 200),
            ing("Onion", "g", 100),
            ing("Garlic", "g", 10),
            ing("Butter", "g", 40),
            ing("All-Purpose Flour", "g", 25),
            ing("Chicken Broth", "ml", 600),
            ing("Heavy Cream", "ml", 150),
            ing("Thyme Fresh", "g", 5),
            ing("Salt", "g", 5),
            ing("Black Pepper", "g", 2),
            ing("Shallot", "g", 30),
        ],
        "prepare_instruction": [
            "Slice all mushrooms. Dice the onion and shallot. Mince the garlic.",
            "Melt butter in a large pot. Add mushrooms and cook over high heat for 8 minutes until deeply browned.",
            "Reduce heat, add onion, shallot, and garlic. Cook for 5 minutes.",
            "Sprinkle flour and stir for 2 minutes.",
            "Pour in chicken broth and add thyme leaves. Bring to a simmer for 15 minutes.",
            "Remove half the soup and blend until smooth. Return to the pot.",
            "Stir in heavy cream, season with salt and pepper.",
            "Serve with a drizzle of cream and fresh thyme.",
        ],
        "time_to_prepare": 2100,
        "total_likes": 187,
    },

    # ==================== SALADS ====================
    {
        "name": "Caesar Salad",
        "author_id": AUTHORS[4],
        "ingredients": [
            ing("Romaine Lettuce", "g", 300),
            ing("Chicken Breast", "g", 200),
            ing("Parmesan Cheese", "g", 50),
            ing("White Bread", "g", 80),
            ing("Garlic", "g", 10),
            ing("Olive Oil", "ml", 40),
            ing("Lemon Juice", "ml", 20),
            ing("Dijon Mustard", "g", 10),
            ing("Anchovies", "g", 15),
            ing("Egg Yolk", "g", 20),
            ing("Salt", "g", 3),
            ing("Black Pepper", "g", 2),
        ],
        "prepare_instruction": [
            "Season chicken breast with salt and pepper. Grill or pan-sear for 6-7 minutes per side until cooked. Let rest, then slice.",
            "Cut bread into cubes. Toss with olive oil and minced garlic. Bake at 190°C for 10 minutes until golden croutons.",
            "For the dressing: blend egg yolk, anchovies, lemon juice, Dijon mustard, and garlic. Slowly drizzle in olive oil while blending.",
            "Wash and tear romaine lettuce into bite-sized pieces.",
            "Toss lettuce with the Caesar dressing until well coated.",
            "Top with sliced chicken, croutons, and shaved Parmesan cheese.",
        ],
        "time_to_prepare": 1800,
        "total_likes": 198,
    },
    {
        "name": "Greek Salad",
        "author_id": AUTHORS[1],
        "ingredients": [
            ing("Tomato", "g", 250),
            ing("Cucumber", "g", 200),
            ing("Red Onion", "g", 60),
            ing("Feta Cheese", "g", 100),
            ing("Black Olives", "g", 60),
            ing("Bell Pepper Green", "g", 80),
            ing("Extra Virgin Olive Oil", "ml", 40),
            ing("Red Wine Vinegar", "ml", 15),
            ing("Oregano Dried", "g", 3),
            ing("Salt", "g", 3),
        ],
        "prepare_instruction": [
            "Cut tomatoes into wedges and cucumber into thick half-moons.",
            "Thinly slice the red onion into rings. Slice the green pepper into strips.",
            "Combine vegetables in a large bowl. Add olives.",
            "Whisk together olive oil, red wine vinegar, dried oregano, and salt.",
            "Pour dressing over the salad and toss gently.",
            "Place a block of feta cheese on top (traditionally uncrumbled). Serve immediately.",
        ],
        "time_to_prepare": 600,
        "total_likes": 167,
    },
    {
        "name": "Caprese Salad",
        "author_id": AUTHORS[1],
        "ingredients": [
            ing("Tomato", "g", 300),
            ing("Mozzarella Cheese", "g", 250),
            ing("Basil Fresh", "g", 20),
            ing("Extra Virgin Olive Oil", "ml", 30),
            ing("Balsamic Vinegar", "ml", 15),
            ing("Salt", "g", 2),
            ing("Black Pepper", "g", 1),
        ],
        "prepare_instruction": [
            "Slice tomatoes and fresh mozzarella into 5mm thick rounds.",
            "Arrange alternating slices of tomato and mozzarella on a serving platter.",
            "Tuck fresh basil leaves between the slices.",
            "Drizzle generously with extra virgin olive oil and balsamic vinegar.",
            "Season with salt and freshly ground black pepper. Serve at room temperature.",
        ],
        "time_to_prepare": 300,
        "total_likes": 145,
    },
    {
        "name": "Asian Sesame Chicken Salad",
        "author_id": AUTHORS[2],
        "ingredients": [
            ing("Chicken Breast", "g", 250),
            ing("Romaine Lettuce", "g", 150),
            ing("Red Cabbage", "g", 100),
            ing("Carrot", "g", 80),
            ing("Cucumber", "g", 80),
            ing("Green Onion", "g", 30),
            ing("Cilantro Fresh", "g", 15),
            ing("Sesame Seeds", "g", 15),
            ing("Soy Sauce", "ml", 30),
            ing("Sesame Oil", "ml", 15),
            ing("Rice Vinegar", "ml", 20),
            ing("Honey", "g", 15),
            ing("Ginger", "g", 5),
        ],
        "prepare_instruction": [
            "Grill or poach chicken breast until cooked through. Let cool, then shred or slice thinly.",
            "Shred romaine lettuce and red cabbage. Julienne carrots and cucumber.",
            "Whisk together soy sauce, sesame oil, rice vinegar, honey, and grated ginger for the dressing.",
            "Combine all vegetables in a large bowl.",
            "Add chicken and pour the dressing over. Toss well.",
            "Garnish with sesame seeds, sliced green onion, and cilantro.",
        ],
        "time_to_prepare": 1200,
        "total_likes": 156,
    },
    {
        "name": "Quinoa Black Bean Salad",
        "author_id": AUTHORS[4],
        "ingredients": [
            ing("Quinoa", "g", 180),
            ing("Black Beans", "g", 200),
            ing("Corn", "g", 120),
            ing("Bell Pepper Red", "g", 100),
            ing("Cherry Tomato", "g", 120),
            ing("Red Onion", "g", 50),
            ing("Avocado", "g", 100),
            ing("Cilantro Fresh", "g", 15),
            ing("Lime Juice", "ml", 30),
            ing("Extra Virgin Olive Oil", "ml", 25),
            ing("Cumin", "g", 2),
            ing("Salt", "g", 3),
        ],
        "prepare_instruction": [
            "Rinse quinoa and cook in salted water according to package directions. Fluff with a fork and let cool.",
            "Drain and rinse black beans. If using frozen corn, thaw or char in a dry pan.",
            "Dice bell pepper, halve cherry tomatoes, finely dice red onion, and cube avocado.",
            "Whisk together lime juice, olive oil, cumin, and salt for the dressing.",
            "In a large bowl, combine quinoa, black beans, corn, bell pepper, tomatoes, and red onion.",
            "Pour dressing over and toss gently. Fold in avocado and cilantro just before serving.",
        ],
        "time_to_prepare": 1200,
        "total_likes": 189,
    },

    # ==================== CHICKEN / POULTRY ====================
    {
        "name": "Grilled Herb Chicken Breast",
        "author_id": AUTHORS[0],
        "ingredients": [
            ing("Chicken Breast", "g", 500),
            ing("Extra Virgin Olive Oil", "ml", 30),
            ing("Lemon Juice", "ml", 30),
            ing("Garlic", "g", 15),
            ing("Rosemary Fresh", "g", 8),
            ing("Thyme Fresh", "g", 5),
            ing("Oregano Dried", "g", 3),
            ing("Salt", "g", 5),
            ing("Black Pepper", "g", 3),
        ],
        "prepare_instruction": [
            "Combine olive oil, lemon juice, minced garlic, chopped rosemary, thyme, oregano, salt, and pepper in a bowl.",
            "Place chicken breasts in a dish and pour the marinade over. Coat evenly.",
            "Cover and refrigerate for at least 30 minutes, up to 4 hours.",
            "Preheat grill to medium-high heat (200°C).",
            "Grill chicken for 6-7 minutes per side until internal temperature reaches 74°C.",
            "Let rest for 5 minutes before slicing. Serve with lemon wedges.",
        ],
        "time_to_prepare": 2400,
        "total_likes": 134,
    },
    {
        "name": "Chicken Stir-Fry",
        "author_id": AUTHORS[2],
        "ingredients": [
            ing("Chicken Breast", "g", 400),
            ing("Broccoli", "g", 150),
            ing("Bell Pepper Red", "g", 100),
            ing("Carrot", "g", 80),
            ing("Snow Peas", "g", 80),
            ing("Garlic", "g", 10),
            ing("Ginger", "g", 10),
            ing("Soy Sauce", "ml", 40),
            ing("Oyster Sauce", "ml", 20),
            ing("Sesame Oil", "ml", 10),
            ing("Cornstarch", "g", 15),
            ing("Vegetable Oil", "ml", 20),
            ing("White Rice", "g", 300),
        ],
        "prepare_instruction": [
            "Cut chicken into thin strips. Toss with half the soy sauce and cornstarch. Let marinate for 15 minutes.",
            "Cut broccoli into small florets, slice bell pepper and carrot into thin strips, trim snow peas.",
            "Cook rice according to package directions.",
            "Heat vegetable oil in a wok over high heat until smoking. Add chicken and stir-fry for 4-5 minutes until golden. Remove.",
            "In the same wok, add garlic and ginger. Cook for 30 seconds.",
            "Add vegetables and stir-fry for 3-4 minutes until crisp-tender.",
            "Return chicken to the wok. Add remaining soy sauce, oyster sauce, and sesame oil. Toss well.",
            "Serve immediately over steamed rice.",
        ],
        "time_to_prepare": 1800,
        "total_likes": 267,
    },
    {
        "name": "Chicken Tikka Masala",
        "author_id": AUTHORS[3],
        "ingredients": [
            ing("Chicken Thigh", "g", 600),
            ing("Greek Yogurt", "g", 100),
            ing("Canned Tomatoes", "g", 400),
            ing("Heavy Cream", "ml", 120),
            ing("Onion", "g", 150),
            ing("Garlic", "g", 20),
            ing("Ginger", "g", 15),
            ing("Garam Masala", "g", 10),
            ing("Cumin", "g", 5),
            ing("Turmeric", "g", 3),
            ing("Paprika", "g", 5),
            ing("Cayenne Pepper", "g", 2),
            ing("Butter", "g", 30),
            ing("Salt", "g", 5),
            ing("Cilantro Fresh", "g", 15),
            ing("Basmati Rice", "g", 300),
        ],
        "prepare_instruction": [
            "Cut chicken thighs into bite-size pieces. Marinate in yogurt, half the garam masala, turmeric, and salt for at least 1 hour.",
            "Thread marinated chicken onto skewers or place on a baking tray. Broil for 10-12 minutes until charred.",
            "Dice onion, mince garlic and ginger.",
            "Melt butter in a large pan. Sauté onion for 5 minutes until soft.",
            "Add garlic, ginger, remaining garam masala, cumin, paprika, and cayenne. Cook for 2 minutes.",
            "Add canned tomatoes and simmer for 15 minutes. Blend until smooth.",
            "Stir in heavy cream and the broiled chicken pieces. Simmer for 10 more minutes.",
            "Cook basmati rice according to package directions.",
            "Garnish with fresh cilantro and serve with basmati rice.",
        ],
        "time_to_prepare": 3600,
        "total_likes": 456,
    },
    {
        "name": "Lemon Herb Roasted Chicken",
        "author_id": AUTHORS[0],
        "ingredients": [
            ing("Chicken Thigh", "g", 800),
            ing("Lemon", "g", 100),
            ing("Garlic", "g", 20),
            ing("Rosemary Fresh", "g", 10),
            ing("Thyme Fresh", "g", 8),
            ing("Olive Oil", "ml", 40),
            ing("Butter", "g", 30),
            ing("Potato", "g", 400),
            ing("Salt", "g", 8),
            ing("Black Pepper", "g", 3),
        ],
        "prepare_instruction": [
            "Preheat oven to 200°C. Cut potatoes into quarters.",
            "Zest and juice the lemon. Mince the garlic. Chop rosemary and thyme.",
            "Mix olive oil, lemon zest, lemon juice, garlic, herbs, salt, and pepper.",
            "Toss chicken thighs and potatoes with the herb mixture in a roasting pan.",
            "Dot pieces of butter over the top.",
            "Roast for 40-45 minutes until chicken skin is golden and crispy, and internal temperature reaches 74°C.",
            "Let rest for 5 minutes. Squeeze remaining lemon halves over the dish before serving.",
        ],
        "time_to_prepare": 3600,
        "total_likes": 312,
    },
    {
        "name": "Chicken Parmesan",
        "author_id": AUTHORS[1],
        "ingredients": [
            ing("Chicken Breast", "g", 500),
            ing("Mozzarella Cheese", "g", 150),
            ing("Parmesan Cheese", "g", 50),
            ing("Tomato Sauce", "g", 300),
            ing("Breadcrumbs", "g", 100),
            ing("All-Purpose Flour", "g", 50),
            ing("Egg", "pcs", 2),
            ing("Olive Oil", "ml", 50),
            ing("Garlic", "g", 10),
            ing("Basil Fresh", "g", 10),
            ing("Salt", "g", 5),
            ing("Black Pepper", "g", 2),
            ing("Spaghetti", "g", 300),
        ],
        "prepare_instruction": [
            "Preheat oven to 200°C. Butterfly or pound chicken breasts to even thickness (about 1.5 cm).",
            "Set up three shallow dishes: flour seasoned with salt and pepper, beaten eggs, breadcrumbs mixed with half the Parmesan.",
            "Dredge each chicken breast in flour, dip in egg, then coat in breadcrumb mixture.",
            "Heat olive oil in an oven-safe skillet. Pan-fry chicken for 3 minutes per side until golden.",
            "Spoon tomato sauce over each chicken breast. Top with sliced mozzarella and remaining Parmesan.",
            "Transfer to oven and bake for 15 minutes until cheese is melted and bubbly.",
            "Meanwhile, cook spaghetti in salted boiling water according to package directions.",
            "Serve chicken Parmesan over spaghetti, garnished with fresh basil.",
        ],
        "time_to_prepare": 2700,
        "total_likes": 378,
    },
    {
        "name": "Teriyaki Chicken",
        "author_id": AUTHORS[2],
        "ingredients": [
            ing("Chicken Thigh", "g", 500),
            ing("Soy Sauce", "ml", 60),
            ing("Honey", "g", 40),
            ing("Rice Vinegar", "ml", 20),
            ing("Garlic", "g", 10),
            ing("Ginger", "g", 10),
            ing("Cornstarch", "g", 10),
            ing("Sesame Seeds", "g", 10),
            ing("Green Onion", "g", 20),
            ing("Vegetable Oil", "ml", 15),
            ing("Jasmine Rice", "g", 300),
            ing("Broccoli", "g", 200),
        ],
        "prepare_instruction": [
            "Mix soy sauce, honey, rice vinegar, minced garlic, grated ginger, and cornstarch mixed with 2 tbsp water for the teriyaki sauce.",
            "Cut chicken thighs into pieces if desired, or keep whole.",
            "Heat vegetable oil in a skillet over medium-high heat. Cook chicken for 5-6 minutes per side until golden.",
            "Pour teriyaki sauce over the chicken. Simmer for 5 minutes, turning chicken to coat, until sauce thickens.",
            "Steam broccoli and cook jasmine rice according to package directions.",
            "Serve chicken over rice with steamed broccoli, drizzled with extra sauce.",
            "Garnish with sesame seeds and sliced green onion.",
        ],
        "time_to_prepare": 1800,
        "total_likes": 298,
    },

    # ==================== BEEF / PORK ====================
    {
        "name": "Classic Beef Burger",
        "author_id": AUTHORS[4],
        "ingredients": [
            ing("Ground Beef Lean", "g", 500),
            ing("White Bread", "g", 200),
            ing("Cheddar Cheese", "g", 80),
            ing("Romaine Lettuce", "g", 60),
            ing("Tomato", "g", 100),
            ing("Red Onion", "g", 50),
            ing("Pickles", "g", 40),
            ing("Ketchup", "g", 30),
            ing("Yellow Mustard", "g", 15),
            ing("Salt", "g", 5),
            ing("Black Pepper", "g", 3),
        ],
        "prepare_instruction": [
            "Divide ground beef into 4 equal portions. Form into patties about 2 cm thick, slightly wider than the buns.",
            "Season both sides generously with salt and pepper.",
            "Heat a grill or cast-iron skillet to high heat.",
            "Cook patties for 3-4 minutes per side for medium. Place cheese on top during the last minute and cover to melt.",
            "Toast the bun halves cut-side down for 1 minute.",
            "Assemble: bottom bun, lettuce, patty with cheese, tomato slice, onion rings, pickles.",
            "Add ketchup and mustard. Crown with top bun and serve immediately.",
        ],
        "time_to_prepare": 1200,
        "total_likes": 345,
    },
    {
        "name": "Beef Tacos",
        "author_id": AUTHORS[4],
        "ingredients": [
            ing("Ground Beef Lean", "g", 400),
            ing("Corn Tortilla", "pcs", 8),
            ing("Onion", "g", 80),
            ing("Garlic", "g", 10),
            ing("Tomato", "g", 120),
            ing("Avocado", "g", 100),
            ing("Sour Cream", "g", 60),
            ing("Cilantro Fresh", "g", 15),
            ing("Lime Juice", "ml", 20),
            ing("Cumin", "g", 5),
            ing("Chili Flakes", "g", 2),
            ing("Paprika", "g", 3),
            ing("Salt", "g", 4),
        ],
        "prepare_instruction": [
            "Dice the onion and mince the garlic. Dice tomato and cube avocado.",
            "Heat a skillet over medium-high heat. Brown the ground beef, breaking it up with a spatula.",
            "Add diced onion and garlic. Cook for 3 minutes.",
            "Season with cumin, paprika, chili flakes, and salt. Stir well and cook for 2 more minutes.",
            "Warm corn tortillas in a dry pan for 30 seconds per side.",
            "Fill each tortilla with seasoned beef.",
            "Top with diced tomato, avocado, sour cream, cilantro, and a squeeze of lime.",
        ],
        "time_to_prepare": 1500,
        "total_likes": 289,
    },
    {
        "name": "Steak with Garlic Butter",
        "author_id": AUTHORS[0],
        "ingredients": [
            ing("Beef Sirloin", "g", 500),
            ing("Butter", "g", 50),
            ing("Garlic", "g", 15),
            ing("Rosemary Fresh", "g", 5),
            ing("Thyme Fresh", "g", 5),
            ing("Olive Oil", "ml", 15),
            ing("Salt", "g", 5),
            ing("Black Pepper", "g", 3),
            ing("Asparagus", "g", 200),
        ],
        "prepare_instruction": [
            "Take steaks out of the fridge 30 minutes before cooking. Pat dry and season generously with salt and pepper.",
            "Heat olive oil in a cast-iron skillet over high heat until smoking.",
            "Sear steaks for 3-4 minutes per side for medium-rare (adjust for desired doneness).",
            "In the last minute, add butter, garlic, rosemary, and thyme to the pan. Baste steaks with the foaming butter.",
            "Remove steaks and let rest for 5 minutes on a cutting board.",
            "In the same pan, sauté asparagus spears for 3-4 minutes until crisp-tender.",
            "Serve steaks with asparagus, spooning the garlic herb butter from the pan over top.",
        ],
        "time_to_prepare": 1800,
        "total_likes": 412,
    },
    {
        "name": "Spaghetti Bolognese",
        "author_id": AUTHORS[1],
        "ingredients": [
            ing("Spaghetti", "g", 400),
            ing("Ground Beef Lean", "g", 500),
            ing("Canned Tomatoes", "g", 400),
            ing("Tomato Paste", "g", 30),
            ing("Onion", "g", 120),
            ing("Carrot", "g", 80),
            ing("Celery", "g", 60),
            ing("Garlic", "g", 15),
            ing("Red Wine", "ml", 100),
            ing("Olive Oil", "ml", 25),
            ing("Bay Leaves", "g", 2),
            ing("Oregano Dried", "g", 3),
            ing("Salt", "g", 5),
            ing("Black Pepper", "g", 2),
            ing("Parmesan Cheese", "g", 50),
            ing("Basil Fresh", "g", 10),
        ],
        "prepare_instruction": [
            "Finely dice the onion, carrot, and celery (soffritto). Mince the garlic.",
            "Heat olive oil in a large heavy-bottomed pot. Brown the ground beef over high heat for 5 minutes, breaking into small pieces.",
            "Add the soffritto and garlic. Cook for 5 minutes until softened.",
            "Stir in tomato paste and cook for 1 minute.",
            "Pour in red wine and let it reduce by half, about 3 minutes.",
            "Add canned tomatoes, bay leaves, and oregano. Season with salt and pepper.",
            "Bring to a simmer. Cover partially and cook on low heat for at least 45 minutes, stirring occasionally.",
            "Cook spaghetti in well-salted boiling water until al dente. Reserve a cup of pasta water.",
            "Toss spaghetti with the sauce, adding pasta water if needed for consistency.",
            "Serve topped with grated Parmesan and fresh basil leaves.",
        ],
        "time_to_prepare": 4200,
        "total_likes": 523,
    },
    {
        "name": "Beef Stew",
        "author_id": AUTHORS[0],
        "ingredients": [
            ing("Beef Chuck", "g", 600),
            ing("Potato", "g", 300),
            ing("Carrot", "g", 200),
            ing("Onion", "g", 150),
            ing("Celery", "g", 80),
            ing("Garlic", "g", 15),
            ing("Tomato Paste", "g", 30),
            ing("Beef Broth", "ml", 800),
            ing("Red Wine", "ml", 200),
            ing("All-Purpose Flour", "g", 30),
            ing("Olive Oil", "ml", 30),
            ing("Bay Leaves", "g", 2),
            ing("Thyme Dried", "g", 3),
            ing("Rosemary Fresh", "g", 5),
            ing("Salt", "g", 8),
            ing("Black Pepper", "g", 3),
            ing("Peas", "g", 100),
        ],
        "prepare_instruction": [
            "Cut beef chuck into 4 cm cubes. Pat dry and season with salt and pepper. Toss with flour.",
            "Heat olive oil in a Dutch oven over high heat. Brown beef in batches, getting a deep sear. Set aside.",
            "Dice onion, carrot, celery, and potatoes into chunks.",
            "Sauté onion and celery for 5 minutes. Add garlic and tomato paste. Cook for 1 minute.",
            "Pour in red wine, scraping up any browned bits from the bottom. Reduce by half.",
            "Return beef to the pot. Add beef broth, bay leaves, thyme, and rosemary.",
            "Bring to a boil, then reduce to a low simmer. Cover and cook for 1.5 hours.",
            "Add potatoes and carrots. Continue cooking for 30 minutes until vegetables are tender.",
            "Add peas in the last 5 minutes. Adjust seasoning and serve hot.",
        ],
        "time_to_prepare": 7800,
        "total_likes": 367,
    },
    {
        "name": "Pork Chops with Apple Sauce",
        "author_id": AUTHORS[3],
        "ingredients": [
            ing("Pork Chop", "g", 600),
            ing("Apple", "g", 300),
            ing("Butter", "g", 30),
            ing("Brown Sugar", "g", 20),
            ing("Cinnamon", "g", 2),
            ing("Lemon Juice", "ml", 15),
            ing("Olive Oil", "ml", 20),
            ing("Salt", "g", 5),
            ing("Black Pepper", "g", 2),
            ing("Sage Fresh", "g", 5),
            ing("Garlic", "g", 10),
        ],
        "prepare_instruction": [
            "Take pork chops out of the fridge 20 minutes before cooking. Season both sides with salt and pepper.",
            "Peel, core, and dice the apples.",
            "Heat olive oil in a large skillet over high heat. Sear pork chops for 4 minutes per side until golden. Set aside.",
            "In the same pan, melt butter. Add diced apples, brown sugar, cinnamon, and lemon juice.",
            "Cook apples for 8-10 minutes, stirring, until softened. Mash slightly for a chunky sauce.",
            "Add minced garlic and sage, cook for 1 minute.",
            "Return pork chops to the pan, nestling them in the apple sauce. Cook for 3-4 minutes until heated through.",
            "Serve pork chops with the apple sauce spooned over the top.",
        ],
        "time_to_prepare": 2400,
        "total_likes": 178,
    },
    {
        "name": "BBQ Pulled Pork",
        "author_id": AUTHORS[4],
        "ingredients": [
            ing("Pork Loin", "g", 1000),
            ing("Ketchup", "g", 100),
            ing("Brown Sugar", "g", 50),
            ing("Apple Cider Vinegar", "ml", 50),
            ing("Worcestershire Sauce", "ml", 30),
            ing("Smoked Paprika", "g", 10),
            ing("Garlic Powder", "g", 5),
            ing("Onion Powder", "g", 5),
            ing("Cumin", "g", 3),
            ing("Cayenne Pepper", "g", 2),
            ing("Salt", "g", 8),
            ing("Black Pepper", "g", 3),
            ing("White Bread", "g", 300),
            ing("Cabbage", "g", 150),
        ],
        "prepare_instruction": [
            "Mix smoked paprika, garlic powder, onion powder, cumin, cayenne, salt, and pepper for a dry rub.",
            "Rub the spice mixture all over the pork loin. Let it sit for at least 30 minutes.",
            "Combine ketchup, brown sugar, apple cider vinegar, and Worcestershire sauce for the BBQ sauce.",
            "Place pork in a slow cooker or Dutch oven. Pour the BBQ sauce over it.",
            "Cook low and slow: 8 hours on low in a slow cooker, or 3 hours at 150°C in the oven (covered).",
            "Shred the meat with two forks. Mix with the pan juices and additional BBQ sauce.",
            "Make a simple coleslaw: shred cabbage and toss with a bit of the BBQ sauce.",
            "Pile the pulled pork onto bread or buns and top with coleslaw.",
        ],
        "time_to_prepare": 10800,
        "total_likes": 345,
    },

    # ==================== FISH / SEAFOOD ====================
    {
        "name": "Pan-Seared Salmon with Lemon Dill",
        "author_id": AUTHORS[0],
        "ingredients": [
            ing("Salmon", "g", 500),
            ing("Lemon", "g", 60),
            ing("Dill Fresh", "g", 15),
            ing("Butter", "g", 30),
            ing("Garlic", "g", 10),
            ing("Olive Oil", "ml", 15),
            ing("Salt", "g", 4),
            ing("Black Pepper", "g", 2),
            ing("Asparagus", "g", 200),
        ],
        "prepare_instruction": [
            "Pat salmon fillets dry with paper towels. Season with salt and pepper.",
            "Heat olive oil in a non-stick skillet over medium-high heat.",
            "Place salmon skin-side up and sear for 4 minutes until a golden crust forms.",
            "Flip carefully. Add butter, minced garlic, and lemon slices to the pan.",
            "Baste salmon with the foaming butter for 3-4 minutes until cooked through.",
            "In a separate pan, sauté asparagus with a drizzle of olive oil for 3-4 minutes.",
            "Serve salmon over asparagus, spooning garlic butter over the top. Garnish with fresh dill and lemon.",
        ],
        "time_to_prepare": 1200,
        "total_likes": 356,
    },
    {
        "name": "Garlic Butter Shrimp",
        "author_id": AUTHORS[1],
        "ingredients": [
            ing("Shrimp", "g", 500),
            ing("Butter", "g", 60),
            ing("Garlic", "g", 20),
            ing("White Wine", "ml", 60),
            ing("Lemon Juice", "ml", 25),
            ing("Chili Flakes", "g", 2),
            ing("Parsley Fresh", "g", 15),
            ing("Salt", "g", 3),
            ing("Black Pepper", "g", 2),
            ing("Spaghetti", "g", 300),
        ],
        "prepare_instruction": [
            "Peel and devein shrimp, leaving tails on. Pat dry and season with salt and pepper.",
            "Cook spaghetti in salted boiling water until al dente. Reserve 1 cup of pasta water.",
            "Melt half the butter in a large skillet over medium-high heat.",
            "Add shrimp in a single layer. Cook 2 minutes per side until pink and curled. Remove and set aside.",
            "In the same pan, add remaining butter and minced garlic. Cook for 1 minute.",
            "Add white wine and lemon juice. Let reduce for 2 minutes.",
            "Return shrimp to the pan. Add chili flakes and toss to coat.",
            "Add drained spaghetti and toss with the sauce, adding pasta water as needed.",
            "Garnish with fresh parsley and serve immediately.",
        ],
        "time_to_prepare": 1500,
        "total_likes": 287,
    },
    {
        "name": "Fish Tacos with Lime Crema",
        "author_id": AUTHORS[4],
        "ingredients": [
            ing("Cod", "g", 400),
            ing("Corn Tortilla", "pcs", 8),
            ing("Red Cabbage", "g", 120),
            ing("Avocado", "g", 100),
            ing("Sour Cream", "g", 80),
            ing("Lime Juice", "ml", 30),
            ing("Cilantro Fresh", "g", 15),
            ing("Cumin", "g", 3),
            ing("Smoked Paprika", "g", 3),
            ing("Garlic Powder", "g", 2),
            ing("Olive Oil", "ml", 20),
            ing("Salt", "g", 4),
        ],
        "prepare_instruction": [
            "Mix cumin, smoked paprika, garlic powder, and salt. Rub onto cod fillets.",
            "Shred red cabbage finely. Cube the avocado.",
            "Make lime crema by mixing sour cream with half the lime juice and a pinch of salt.",
            "Heat olive oil in a skillet. Cook cod for 3-4 minutes per side until flaky. Break into large chunks.",
            "Warm tortillas in a dry pan for 30 seconds per side.",
            "Assemble tacos: layer shredded cabbage, fish, avocado, and drizzle of lime crema.",
            "Top with cilantro and a squeeze of fresh lime juice.",
        ],
        "time_to_prepare": 1200,
        "total_likes": 234,
    },
    {
        "name": "Tuna Poke Bowl",
        "author_id": AUTHORS[2],
        "ingredients": [
            ing("Tuna Fresh", "g", 350),
            ing("Jasmine Rice", "g", 300),
            ing("Avocado", "g", 120),
            ing("Cucumber", "g", 100),
            ing("Carrot", "g", 60),
            ing("Edamame", "g", 80),
            ing("Soy Sauce", "ml", 40),
            ing("Sesame Oil", "ml", 15),
            ing("Rice Vinegar", "ml", 10),
            ing("Nori Seaweed", "g", 5),
            ing("Sesame Seeds", "g", 10),
            ing("Green Onion", "g", 15),
            ing("Ginger", "g", 5),
            ing("Sriracha", "ml", 10),
        ],
        "prepare_instruction": [
            "Cook jasmine rice and let it cool slightly. Season with a splash of rice vinegar.",
            "Cut sushi-grade tuna into 1.5 cm cubes.",
            "Marinate tuna in soy sauce, sesame oil, grated ginger, and rice vinegar for 15 minutes.",
            "Slice avocado and cucumber. Julienne the carrot. Cook edamame if frozen.",
            "Divide rice among bowls.",
            "Arrange marinated tuna, avocado, cucumber, carrot, and edamame on top of the rice.",
            "Drizzle with sriracha, sprinkle sesame seeds, sliced green onion, and torn nori.",
        ],
        "time_to_prepare": 1800,
        "total_likes": 256,
    },
    {
        "name": "Baked Cod with Herbs",
        "author_id": AUTHORS[3],
        "ingredients": [
            ing("Cod", "g", 500),
            ing("Lemon Juice", "ml", 25),
            ing("Butter", "g", 30),
            ing("Garlic", "g", 10),
            ing("Parsley Fresh", "g", 15),
            ing("Dill Fresh", "g", 10),
            ing("Panko Breadcrumbs", "g", 40),
            ing("Olive Oil", "ml", 15),
            ing("Salt", "g", 4),
            ing("Black Pepper", "g", 2),
            ing("Cherry Tomato", "g", 150),
        ],
        "prepare_instruction": [
            "Preheat oven to 200°C. Line a baking sheet with parchment paper.",
            "Place cod fillets on the prepared baking sheet. Season with salt, pepper, and lemon juice.",
            "Mix melted butter, minced garlic, chopped parsley, dill, and panko breadcrumbs.",
            "Press the breadcrumb mixture evenly onto the top of each cod fillet.",
            "Scatter cherry tomatoes around the fish. Drizzle everything with olive oil.",
            "Bake for 15-18 minutes until the fish flakes easily and the crust is golden.",
            "Serve with the roasted cherry tomatoes alongside.",
        ],
        "time_to_prepare": 1500,
        "total_likes": 189,
    },

    # ==================== PASTA ====================
    {
        "name": "Spaghetti Carbonara",
        "author_id": AUTHORS[1],
        "ingredients": [
            ing("Spaghetti", "g", 400),
            ing("Pancetta", "g", 150),
            ing("Egg Yolk", "g", 80),
            ing("Egg", "pcs", 2),
            ing("Parmesan Cheese", "g", 80),
            ing("Black Pepper", "g", 5),
            ing("Salt", "g", 5),
        ],
        "prepare_instruction": [
            "Cook spaghetti in a large pot of well-salted boiling water until al dente. Reserve 200ml of pasta water.",
            "While pasta cooks, cut pancetta into small cubes. Cook in a large cold skillet over medium heat until fat renders and pancetta is crispy, about 8 minutes.",
            "In a bowl, whisk together egg yolks, whole eggs, grated Parmesan, and generous black pepper.",
            "When pasta is ready, drain and add it to the skillet with the pancetta. Remove from heat.",
            "Pour the egg and cheese mixture over the hot pasta. Toss vigorously — the residual heat will cook the eggs into a creamy sauce.",
            "Add pasta water a splash at a time if the sauce is too thick.",
            "Serve immediately with extra Parmesan and black pepper on top.",
        ],
        "time_to_prepare": 1200,
        "total_likes": 567,
    },
    {
        "name": "Spaghetti Aglio e Olio",
        "author_id": AUTHORS[1],
        "ingredients": [
            ing("Spaghetti", "g", 400),
            ing("Garlic", "g", 30),
            ing("Extra Virgin Olive Oil", "ml", 80),
            ing("Chili Flakes", "g", 3),
            ing("Parsley Fresh", "g", 20),
            ing("Salt", "g", 5),
            ing("Parmesan Cheese", "g", 30),
        ],
        "prepare_instruction": [
            "Cook spaghetti in well-salted boiling water until al dente. Reserve 200ml of pasta water before draining.",
            "While pasta cooks, thinly slice the garlic (do not mince — slices stay softer).",
            "In a large skillet, heat olive oil over medium-low heat. Add garlic slices and cook gently for 2-3 minutes until golden (not brown!).",
            "Add chili flakes and cook for 30 seconds.",
            "Add drained pasta directly to the skillet along with a splash of pasta water.",
            "Toss vigorously over medium heat, adding more pasta water as needed until a silky sauce forms.",
            "Remove from heat, add chopped parsley, and toss again. Serve with Parmesan on the side.",
        ],
        "time_to_prepare": 900,
        "total_likes": 445,
    },
    {
        "name": "Pesto Pasta",
        "author_id": AUTHORS[1],
        "ingredients": [
            ing("Fusilli", "g", 400),
            ing("Basil Fresh", "g", 60),
            ing("Pine Nuts", "g", 40),
            ing("Parmesan Cheese", "g", 60),
            ing("Garlic", "g", 10),
            ing("Extra Virgin Olive Oil", "ml", 80),
            ing("Lemon Juice", "ml", 10),
            ing("Salt", "g", 3),
            ing("Cherry Tomato", "g", 150),
        ],
        "prepare_instruction": [
            "Toast pine nuts in a dry pan over medium heat for 2-3 minutes until golden. Watch carefully — they burn quickly.",
            "In a food processor, combine basil, toasted pine nuts, garlic, and Parmesan. Pulse until roughly chopped.",
            "With the processor running, drizzle in olive oil in a steady stream until a smooth pesto forms.",
            "Season pesto with salt and lemon juice.",
            "Cook fusilli in salted boiling water until al dente. Reserve 100ml pasta water.",
            "Toss hot pasta with pesto, adding pasta water to loosen the sauce.",
            "Serve topped with halved cherry tomatoes and extra Parmesan shavings.",
        ],
        "time_to_prepare": 1200,
        "total_likes": 356,
    },
    {
        "name": "Mac and Cheese",
        "author_id": AUTHORS[4],
        "ingredients": [
            ing("Penne", "g", 400),
            ing("Cheddar Cheese", "g", 250),
            ing("Whole Milk", "ml", 400),
            ing("Butter", "g", 40),
            ing("All-Purpose Flour", "g", 30),
            ing("Nutmeg", "g", 1),
            ing("Salt", "g", 5),
            ing("Black Pepper", "g", 2),
            ing("Panko Breadcrumbs", "g", 50),
            ing("Parmesan Cheese", "g", 30),
        ],
        "prepare_instruction": [
            "Preheat oven to 190°C. Cook penne until just barely al dente (it will continue cooking in the oven).",
            "Melt butter in a saucepan over medium heat. Whisk in flour and cook for 2 minutes, stirring constantly.",
            "Gradually whisk in milk, ensuring no lumps. Cook over medium heat, whisking, until sauce thickens (about 5 minutes).",
            "Remove from heat. Stir in most of the grated cheddar until melted and smooth. Season with nutmeg, salt, and pepper.",
            "Combine cooked pasta with the cheese sauce. Pour into a baking dish.",
            "Mix panko breadcrumbs with remaining cheddar and Parmesan. Scatter over the top.",
            "Bake for 20-25 minutes until golden and bubbly. Let rest 5 minutes before serving.",
        ],
        "time_to_prepare": 2700,
        "total_likes": 423,
    },
    {
        "name": "Classic Lasagna",
        "author_id": AUTHORS[1],
        "ingredients": [
            ing("Lasagna Sheets", "g", 300),
            ing("Ground Beef Lean", "g", 500),
            ing("Italian Sausage", "g", 200),
            ing("Ricotta Cheese", "g", 400),
            ing("Mozzarella Cheese", "g", 300),
            ing("Parmesan Cheese", "g", 80),
            ing("Canned Tomatoes", "g", 800),
            ing("Tomato Paste", "g", 40),
            ing("Onion", "g", 120),
            ing("Garlic", "g", 15),
            ing("Egg", "pcs", 1),
            ing("Basil Fresh", "g", 15),
            ing("Oregano Dried", "g", 5),
            ing("Salt", "g", 8),
            ing("Black Pepper", "g", 3),
            ing("Olive Oil", "ml", 20),
        ],
        "prepare_instruction": [
            "Heat olive oil in a large pot. Brown ground beef and crumbled sausage. Drain excess fat.",
            "Add diced onion and garlic. Cook for 5 minutes.",
            "Stir in canned tomatoes, tomato paste, basil, and oregano. Simmer for 30 minutes.",
            "In a bowl, mix ricotta with egg, half the Parmesan, salt, and pepper.",
            "Preheat oven to 190°C.",
            "Spread a thin layer of meat sauce in a 9x13 baking dish.",
            "Layer: lasagna sheets, ricotta mixture, meat sauce, mozzarella. Repeat 3 times.",
            "Top with remaining sauce, mozzarella, and Parmesan.",
            "Cover with foil and bake for 25 minutes. Remove foil and bake 15 more minutes until bubbly.",
            "Let rest 15 minutes before cutting. This is crucial for clean slices.",
        ],
        "time_to_prepare": 5400,
        "total_likes": 489,
    },

    # ==================== VEGETARIAN ====================
    {
        "name": "Vegetable Curry",
        "author_id": AUTHORS[3],
        "ingredients": [
            ing("Potato", "g", 200),
            ing("Cauliflower", "g", 200),
            ing("Chickpeas", "g", 200),
            ing("Spinach", "g", 100),
            ing("Onion", "g", 120),
            ing("Garlic", "g", 15),
            ing("Ginger", "g", 15),
            ing("Canned Tomatoes", "g", 400),
            ing("Coconut Milk", "ml", 400),
            ing("Curry Powder", "g", 15),
            ing("Garam Masala", "g", 5),
            ing("Turmeric", "g", 3),
            ing("Vegetable Oil", "ml", 20),
            ing("Salt", "g", 5),
            ing("Cilantro Fresh", "g", 15),
            ing("Basmati Rice", "g", 300),
        ],
        "prepare_instruction": [
            "Peel and dice potatoes into 2 cm cubes. Break cauliflower into small florets.",
            "Dice the onion. Mince garlic and ginger.",
            "Heat oil in a large pot. Sauté onion for 5 minutes until softened.",
            "Add garlic, ginger, curry powder, garam masala, and turmeric. Cook for 2 minutes.",
            "Add canned tomatoes, coconut milk, potatoes, cauliflower, and chickpeas.",
            "Bring to a boil, then reduce heat and simmer for 20-25 minutes until potatoes are tender.",
            "Stir in spinach and cook for 2 more minutes until wilted.",
            "Cook basmati rice according to package directions.",
            "Season curry with salt, garnish with cilantro, and serve over rice.",
        ],
        "time_to_prepare": 2700,
        "total_likes": 312,
    },
    {
        "name": "Stuffed Bell Peppers",
        "author_id": AUTHORS[3],
        "ingredients": [
            ing("Bell Pepper Red", "g", 400),
            ing("White Rice", "g", 150),
            ing("Ground Turkey", "g", 300),
            ing("Onion", "g", 80),
            ing("Garlic", "g", 10),
            ing("Canned Tomatoes", "g", 200),
            ing("Tomato Sauce", "g", 150),
            ing("Cheddar Cheese", "g", 80),
            ing("Cumin", "g", 3),
            ing("Oregano Dried", "g", 2),
            ing("Salt", "g", 5),
            ing("Black Pepper", "g", 2),
            ing("Olive Oil", "ml", 15),
        ],
        "prepare_instruction": [
            "Preheat oven to 190°C. Cook rice according to package directions.",
            "Cut tops off bell peppers and remove seeds. Stand upright in a baking dish.",
            "Heat olive oil in a skillet. Cook ground turkey with diced onion for 5-7 minutes.",
            "Add garlic, cumin, oregano, salt, and pepper. Cook for 1 minute.",
            "Stir in cooked rice, diced canned tomatoes, and half the tomato sauce.",
            "Fill each pepper with the mixture, pressing down gently. Top with remaining tomato sauce.",
            "Cover with foil and bake for 30 minutes.",
            "Remove foil, top with grated cheddar, and bake uncovered for 10 more minutes.",
        ],
        "time_to_prepare": 3600,
        "total_likes": 198,
    },
    {
        "name": "Eggplant Parmesan",
        "author_id": AUTHORS[1],
        "ingredients": [
            ing("Eggplant", "g", 600),
            ing("Mozzarella Cheese", "g", 200),
            ing("Parmesan Cheese", "g", 60),
            ing("Tomato Sauce", "g", 400),
            ing("Breadcrumbs", "g", 100),
            ing("All-Purpose Flour", "g", 50),
            ing("Egg", "pcs", 2),
            ing("Olive Oil", "ml", 60),
            ing("Basil Fresh", "g", 15),
            ing("Garlic", "g", 10),
            ing("Salt", "g", 8),
            ing("Black Pepper", "g", 2),
        ],
        "prepare_instruction": [
            "Slice eggplant into 1 cm rounds. Salt both sides and let sit for 30 minutes to draw out moisture. Pat dry.",
            "Set up breading station: flour, beaten eggs, breadcrumbs mixed with half the Parmesan.",
            "Dredge each eggplant slice in flour, dip in egg, coat in breadcrumbs.",
            "Pan-fry in olive oil for 2-3 minutes per side until golden. Drain on paper towels.",
            "Preheat oven to 190°C.",
            "Spread a thin layer of tomato sauce in a baking dish. Layer fried eggplant, more sauce, and mozzarella.",
            "Repeat layers, ending with sauce and cheese on top. Sprinkle remaining Parmesan.",
            "Bake for 25-30 minutes until bubbly and golden. Garnish with fresh basil.",
        ],
        "time_to_prepare": 4200,
        "total_likes": 234,
    },
    {
        "name": "Black Bean Burrito Bowl",
        "author_id": AUTHORS[4],
        "ingredients": [
            ing("Black Beans", "g", 300),
            ing("Brown Rice", "g", 200),
            ing("Corn", "g", 120),
            ing("Avocado", "g", 120),
            ing("Cherry Tomato", "g", 120),
            ing("Red Onion", "g", 50),
            ing("Cilantro Fresh", "g", 15),
            ing("Lime Juice", "ml", 30),
            ing("Sour Cream", "g", 60),
            ing("Cumin", "g", 5),
            ing("Smoked Paprika", "g", 3),
            ing("Garlic", "g", 5),
            ing("Hot Sauce", "ml", 10),
            ing("Salt", "g", 3),
        ],
        "prepare_instruction": [
            "Cook brown rice according to package directions. Fluff with a fork.",
            "In a saucepan, warm black beans with cumin, smoked paprika, minced garlic, and salt.",
            "Char corn kernels in a dry hot skillet for 3-4 minutes until slightly blackened.",
            "Halve cherry tomatoes. Dice red onion and avocado.",
            "Mix sour cream with lime juice for a simple lime crema.",
            "Assemble bowls: rice on the bottom, then seasoned black beans, charred corn, tomatoes, avocado, and red onion.",
            "Drizzle with lime crema and hot sauce. Garnish with cilantro.",
        ],
        "time_to_prepare": 1500,
        "total_likes": 267,
    },
    {
        "name": "Mushroom Risotto",
        "author_id": AUTHORS[1],
        "ingredients": [
            ing("Arborio Rice", "g", 300),
            ing("White Mushroom", "g", 200),
            ing("Cremini Mushroom", "g", 100),
            ing("Shiitake Mushroom", "g", 80),
            ing("Onion", "g", 80),
            ing("Garlic", "g", 10),
            ing("White Wine", "ml", 120),
            ing("Chicken Broth", "ml", 1000),
            ing("Parmesan Cheese", "g", 60),
            ing("Butter", "g", 40),
            ing("Olive Oil", "ml", 20),
            ing("Thyme Fresh", "g", 5),
            ing("Salt", "g", 5),
            ing("Black Pepper", "g", 2),
        ],
        "prepare_instruction": [
            "Warm chicken broth in a saucepan and keep at a gentle simmer.",
            "Slice all mushrooms. Heat olive oil in a large pan, sauté mushrooms with thyme until deeply golden, about 8 minutes. Set aside.",
            "In a heavy-bottomed pot, melt half the butter. Sauté finely diced onion for 3 minutes.",
            "Add arborio rice and stir for 2 minutes until edges become translucent.",
            "Pour in white wine and stir until fully absorbed.",
            "Add warm broth one ladle at a time, stirring frequently. Wait until each addition is absorbed before adding more. This takes about 18-20 minutes.",
            "When rice is creamy and al dente, fold in sautéed mushrooms, remaining butter, and Parmesan.",
            "Season with salt and pepper. Serve immediately — risotto waits for no one.",
        ],
        "time_to_prepare": 2400,
        "total_likes": 378,
    },

    # ==================== DESSERTS ====================
    {
        "name": "Chocolate Lava Cake",
        "author_id": AUTHORS[0],
        "ingredients": [
            ing("Dark Chocolate", "g", 150),
            ing("Butter", "g", 100),
            ing("Egg", "pcs", 3),
            ing("Egg Yolk", "g", 40),
            ing("White Sugar", "g", 60),
            ing("All-Purpose Flour", "g", 30),
            ing("Cocoa Powder", "g", 10),
            ing("Vanilla Extract", "ml", 5),
            ing("Salt", "g", 1),
        ],
        "prepare_instruction": [
            "Preheat oven to 220°C. Grease 4 ramekins with butter and dust with cocoa powder.",
            "Melt dark chocolate and butter together in a double boiler or microwave (30-second intervals). Stir until smooth.",
            "In a separate bowl, whisk eggs, egg yolks, and sugar until thick and pale, about 3 minutes.",
            "Fold the melted chocolate into the egg mixture. Add vanilla extract.",
            "Sift in flour and salt. Fold gently until just combined — do not overmix.",
            "Divide batter among the prepared ramekins.",
            "Bake for exactly 12-14 minutes — the edges should be firm but the center jiggly.",
            "Let rest for 1 minute, then invert onto plates. The center should flow like lava when cut.",
        ],
        "time_to_prepare": 1800,
        "total_likes": 456,
    },
    {
        "name": "Banana Bread",
        "author_id": AUTHORS[3],
        "ingredients": [
            ing("Banana", "g", 300),
            ing("All-Purpose Flour", "g", 250),
            ing("White Sugar", "g", 100),
            ing("Butter", "g", 80),
            ing("Egg", "pcs", 2),
            ing("Baking Soda", "g", 5),
            ing("Vanilla Extract", "ml", 5),
            ing("Cinnamon", "g", 3),
            ing("Salt", "g", 2),
            ing("Walnuts", "g", 60),
        ],
        "prepare_instruction": [
            "Preheat oven to 175°C. Grease and line a loaf pan with parchment paper.",
            "Mash ripe bananas in a bowl until smooth with some small lumps remaining.",
            "In a separate bowl, melt butter. Add sugar and mix well.",
            "Beat in eggs one at a time, then add vanilla extract.",
            "Mix in the mashed bananas.",
            "In another bowl, whisk together flour, baking soda, cinnamon, and salt.",
            "Fold the dry ingredients into the wet ingredients until just combined. Fold in chopped walnuts.",
            "Pour batter into the prepared loaf pan.",
            "Bake for 55-65 minutes until a toothpick inserted in the center comes out clean.",
            "Cool in the pan for 10 minutes, then turn out onto a wire rack.",
        ],
        "time_to_prepare": 4800,
        "total_likes": 345,
    },
    {
        "name": "Apple Crumble",
        "author_id": AUTHORS[0],
        "ingredients": [
            ing("Apple", "g", 600),
            ing("Brown Sugar", "g", 60),
            ing("Cinnamon", "g", 5),
            ing("Lemon Juice", "ml", 15),
            ing("All-Purpose Flour", "g", 120),
            ing("Oats", "g", 60),
            ing("Butter", "g", 80),
            ing("White Sugar", "g", 40),
            ing("Nutmeg", "g", 1),
            ing("Salt", "g", 1),
            ing("Vanilla Extract", "ml", 5),
        ],
        "prepare_instruction": [
            "Preheat oven to 180°C.",
            "Peel, core, and slice apples into thin wedges. Toss with brown sugar, cinnamon, lemon juice, and vanilla.",
            "Spread apple mixture in a baking dish.",
            "For the crumble: mix flour, oats, white sugar, nutmeg, and salt in a bowl.",
            "Cut cold butter into small cubes and rub into the dry ingredients with your fingertips until you get a crumbly, sandy texture.",
            "Scatter the crumble topping evenly over the apples.",
            "Bake for 35-40 minutes until the top is golden and the apples are bubbling.",
            "Serve warm with vanilla ice cream or whipped cream.",
        ],
        "time_to_prepare": 3600,
        "total_likes": 278,
    },
    {
        "name": "Panna Cotta",
        "author_id": AUTHORS[1],
        "ingredients": [
            ing("Heavy Cream", "ml", 400),
            ing("Whole Milk", "ml", 100),
            ing("White Sugar", "g", 60),
            ing("Vanilla Extract", "ml", 10),
            ing("Gelatin", "g", 5),
            ing("Strawberry", "g", 150),
            ing("Honey", "g", 20),
        ],
        "prepare_instruction": [
            "Sprinkle gelatin over 3 tablespoons of cold water. Let it bloom for 5 minutes.",
            "In a saucepan, combine cream, milk, and sugar. Heat over medium heat, stirring, until sugar dissolves. Do not boil.",
            "Remove from heat. Add the bloomed gelatin and stir until completely dissolved.",
            "Stir in vanilla extract.",
            "Pour into 4 ramekins or glasses. Refrigerate for at least 4 hours until set.",
            "For the topping: slice strawberries and toss with honey. Let macerate for 30 minutes.",
            "Serve panna cotta topped with macerated strawberries.",
        ],
        "time_to_prepare": 1200,
        "total_likes": 234,
    },
    {
        "name": "Tiramisu",
        "author_id": AUTHORS[1],
        "ingredients": [
            ing("Mascarpone", "g", 500),
            ing("Egg Yolk", "g", 100),
            ing("White Sugar", "g", 80),
            ing("Heavy Cream", "ml", 250),
            ing("Vanilla Extract", "ml", 5),
            ing("Cocoa Powder", "g", 20),
            ing("Dark Chocolate", "g", 30),
        ],
        "prepare_instruction": [
            "Whisk egg yolks with sugar until thick, pale, and the whisk leaves a trail (about 5 minutes).",
            "Add mascarpone and vanilla extract. Fold gently until smooth.",
            "In a separate bowl, whip heavy cream to stiff peaks. Fold into the mascarpone mixture.",
            "Arrange a layer of ladyfinger-style base in a dish.",
            "Spread half the mascarpone cream over the base layer.",
            "Repeat with another layer of base and the remaining cream.",
            "Dust the top generously with cocoa powder. Grate dark chocolate over the surface.",
            "Refrigerate for at least 6 hours (overnight is best) before serving.",
        ],
        "time_to_prepare": 1800,
        "total_likes": 512,
    },

    # ==================== MORE MAINS ====================
    {
        "name": "Thai Green Curry",
        "author_id": AUTHORS[2],
        "ingredients": [
            ing("Chicken Breast", "g", 400),
            ing("Coconut Milk", "ml", 400),
            ing("Green Beans", "g", 100),
            ing("Bell Pepper Green", "g", 100),
            ing("Zucchini", "g", 100),
            ing("Thai Basil", "g", 15),
            ing("Garlic", "g", 10),
            ing("Ginger", "g", 10),
            ing("Fish Sauce", "ml", 20),
            ing("Brown Sugar", "g", 10),
            ing("Lime Juice", "ml", 15),
            ing("Vegetable Oil", "ml", 15),
            ing("Jasmine Rice", "g", 300),
            ing("Chili Pepper", "g", 10),
        ],
        "prepare_instruction": [
            "Slice chicken breast into thin strips. Cut green beans, bell pepper, and zucchini into bite-sized pieces.",
            "Heat oil in a large wok or pot. Sauté minced garlic, ginger, and sliced chili for 1 minute.",
            "Add chicken and stir-fry for 3-4 minutes until white on the outside.",
            "Pour in coconut milk and bring to a simmer.",
            "Add green beans and bell pepper. Cook for 5 minutes.",
            "Add zucchini, fish sauce, and brown sugar. Simmer for 3 more minutes.",
            "Stir in lime juice and Thai basil just before serving.",
            "Cook jasmine rice and serve the curry over it.",
        ],
        "time_to_prepare": 1800,
        "total_likes": 289,
    },
    {
        "name": "Miso Glazed Salmon",
        "author_id": AUTHORS[2],
        "ingredients": [
            ing("Salmon", "g", 500),
            ing("Miso Paste", "g", 50),
            ing("Honey", "g", 25),
            ing("Soy Sauce", "ml", 20),
            ing("Rice Vinegar", "ml", 15),
            ing("Sesame Oil", "ml", 10),
            ing("Ginger", "g", 10),
            ing("Green Onion", "g", 15),
            ing("Sesame Seeds", "g", 10),
            ing("Brown Rice", "g", 200),
            ing("Bok Choy", "g", 200),
        ],
        "prepare_instruction": [
            "Mix miso paste, honey, soy sauce, rice vinegar, sesame oil, and grated ginger for the glaze.",
            "Coat salmon fillets with the miso glaze. Marinate for at least 30 minutes (up to overnight).",
            "Preheat oven to 200°C. Line a baking sheet with parchment paper.",
            "Place salmon skin-side down on the baking sheet.",
            "Bake for 12-15 minutes until the glaze is caramelized and salmon is cooked through.",
            "Meanwhile, cook brown rice and steam bok choy halves for 3-4 minutes.",
            "Serve salmon over rice with bok choy. Garnish with green onion and sesame seeds.",
        ],
        "time_to_prepare": 2400,
        "total_likes": 312,
    },
    {
        "name": "Lamb Kofta with Tzatziki",
        "author_id": AUTHORS[3],
        "ingredients": [
            ing("Ground Lamb", "g", 500),
            ing("Onion", "g", 80),
            ing("Garlic", "g", 10),
            ing("Cumin", "g", 5),
            ing("Coriander Ground", "g", 3),
            ing("Paprika", "g", 3),
            ing("Parsley Fresh", "g", 15),
            ing("Salt", "g", 5),
            ing("Black Pepper", "g", 2),
            ing("Greek Yogurt", "g", 200),
            ing("Cucumber", "g", 100),
            ing("Lemon Juice", "ml", 15),
            ing("Mint Fresh", "g", 10),
            ing("Pita Bread", "g", 200),
            ing("Olive Oil", "ml", 15),
        ],
        "prepare_instruction": [
            "Grate the onion and squeeze out excess moisture. Mix with ground lamb, minced garlic, cumin, coriander, paprika, chopped parsley, salt, and pepper.",
            "Form the mixture into oval-shaped kofta around skewers or as free-form patties.",
            "Grill or pan-fry kofta over high heat for 3-4 minutes per side until charred outside and cooked through.",
            "For tzatziki: grate cucumber and squeeze out water. Mix with Greek yogurt, lemon juice, chopped mint, minced garlic, and salt.",
            "Warm pita bread on the grill or in a pan.",
            "Serve kofta in warm pita with generous tzatziki, extra parsley, and a squeeze of lemon.",
        ],
        "time_to_prepare": 1800,
        "total_likes": 234,
    },
    {
        "name": "Shrimp Pad Thai",
        "author_id": AUTHORS[2],
        "ingredients": [
            ing("Shrimp", "g", 300),
            ing("Rice Noodles", "g", 250),
            ing("Egg", "pcs", 2),
            ing("Bean Sprouts", "g", 100),
            ing("Green Onion", "g", 30),
            ing("Peanuts", "g", 40),
            ing("Garlic", "g", 10),
            ing("Fish Sauce", "ml", 30),
            ing("Lime Juice", "ml", 25),
            ing("Brown Sugar", "g", 30),
            ing("Sriracha", "ml", 10),
            ing("Vegetable Oil", "ml", 20),
            ing("Cilantro Fresh", "g", 10),
        ],
        "prepare_instruction": [
            "Soak rice noodles in warm water for 20 minutes until pliable. Drain.",
            "Mix fish sauce, lime juice, brown sugar, and sriracha for the pad thai sauce.",
            "Heat oil in a wok over high heat. Cook shrimp for 2 minutes per side. Remove and set aside.",
            "In the same wok, scramble eggs. Push to one side.",
            "Add garlic and cook for 30 seconds. Add drained noodles and the sauce.",
            "Toss everything together, adding bean sprouts and returning shrimp.",
            "Cook for 2-3 minutes until noodles are tender and sauce is absorbed.",
            "Serve topped with crushed peanuts, sliced green onion, cilantro, and lime wedges.",
        ],
        "time_to_prepare": 1800,
        "total_likes": 345,
    },
    {
        "name": "Mediterranean Baked Chicken",
        "author_id": AUTHORS[3],
        "ingredients": [
            ing("Chicken Thigh", "g", 600),
            ing("Cherry Tomato", "g", 200),
            ing("Black Olives", "g", 60),
            ing("Feta Cheese", "g", 80),
            ing("Red Onion", "g", 80),
            ing("Garlic", "g", 10),
            ing("Extra Virgin Olive Oil", "ml", 30),
            ing("Oregano Dried", "g", 5),
            ing("Lemon Juice", "ml", 20),
            ing("Salt", "g", 5),
            ing("Black Pepper", "g", 2),
            ing("Basil Fresh", "g", 10),
        ],
        "prepare_instruction": [
            "Preheat oven to 200°C.",
            "Season chicken thighs with oregano, salt, pepper, and half the olive oil.",
            "Arrange chicken in a baking dish. Scatter cherry tomatoes, sliced red onion, and olives around.",
            "Drizzle remaining olive oil and lemon juice over everything.",
            "Bake for 35-40 minutes until chicken is golden and cooked through.",
            "Crumble feta cheese over the hot dish. It will soften slightly from the heat.",
            "Garnish with fresh basil and serve with crusty bread or couscous.",
        ],
        "time_to_prepare": 3000,
        "total_likes": 267,
    },
    {
        "name": "Honey Garlic Chicken Wings",
        "author_id": AUTHORS[4],
        "ingredients": [
            ing("Chicken Wing", "g", 1000),
            ing("Honey", "g", 60),
            ing("Soy Sauce", "ml", 40),
            ing("Garlic", "g", 20),
            ing("Ginger", "g", 10),
            ing("Sriracha", "ml", 15),
            ing("Rice Vinegar", "ml", 15),
            ing("Sesame Seeds", "g", 10),
            ing("Green Onion", "g", 15),
            ing("Cornstarch", "g", 30),
            ing("Salt", "g", 5),
            ing("Vegetable Oil", "ml", 30),
        ],
        "prepare_instruction": [
            "Pat chicken wings dry. Season with salt and toss with cornstarch.",
            "Preheat oven to 220°C. Arrange wings on a wire rack over a baking sheet.",
            "Bake for 45-50 minutes, flipping halfway, until golden and crispy.",
            "While wings bake, make the sauce: combine honey, soy sauce, minced garlic, grated ginger, sriracha, and rice vinegar in a saucepan.",
            "Simmer over medium heat for 5 minutes until slightly thickened.",
            "Toss baked wings in the honey garlic sauce until well coated.",
            "Garnish with sesame seeds and sliced green onion. Serve immediately.",
        ],
        "time_to_prepare": 3600,
        "total_likes": 387,
    },
]


# ---------------------------------------------------------------------------
# Init function
# ---------------------------------------------------------------------------
async def init_recipes():
    """Seed the recipes collection (idempotent — skips if data exists)."""
    try:
        print("Connecting to MongoDB…")
        await connect_to_mongodb()

        db = get_database()
        collection = db[settings.RECIPES_COLLECTION]

        existing_count = await collection.count_documents({})
        if existing_count > 0:
            print(f"⚠️  Collection already has {existing_count} recipes — skipping.")
            return

        docs = []
        for r in RECIPES:
            weighted = [
                WeightedIngredient(**i) for i in r["ingredients"]
            ]
            recipe = Recipe(
                name=r["name"],
                author_id=r["author_id"],
                ingredients=weighted,
                prepare_instruction=r["prepare_instruction"],
                time_to_prepare=r["time_to_prepare"],
                total_likes=r.get("total_likes", 0),
                images=r.get("images"),
            )
            docs.append(recipe.model_dump(by_alias=True))

        result = await collection.insert_many(docs)

        print(f"✅ Inserted {len(result.inserted_ids)} recipes.")

        # Print summary
        for recipe_doc, recipe_data in zip(docs, RECIPES):
            n_ing = len(recipe_data["ingredients"])
            print(f"  • {recipe_data['name']} ({n_ing} ingredients)")

    except Exception as e:
        print(f"❌ Error: {e}")
        raise
    finally:
        await disconnect_from_mongodb()


if __name__ == "__main__":
    print(f"Total recipes to seed: {len(RECIPES)}")
    asyncio.run(init_recipes())
