"""Corrected author_uid to author_id to keep unified notation.

Revision ID: 0c28c1d41b64
Revises: 1f1ed9ae5ab4
Create Date: 2025-12-20 16:40:10.946470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c28c1d41b64'
down_revision: Union[str, Sequence[str], None] = '1f1ed9ae5ab4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author_id', sa.Uuid(), nullable=False))
    op.drop_column('posts', 'author_uid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author_uid', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('posts', 'author_id')
    # ### end Alembic commands ###
