"""Reorganized models structure to make it more managable, packed every model in correct order in __init__ package file.

Revision ID: 1a8808feff76
Revises: cfadcd802dc4
Create Date: 2025-12-18 23:05:31.371924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a8808feff76'
down_revision: Union[str, Sequence[str], None] = 'cfadcd802dc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_likes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('post_uid', sa.Uuid(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['post_uid'], ['posts.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_views',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('post_uid', sa.Uuid(), nullable=False),
    sa.Column('viewed_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('engagement_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_uid'], ['posts.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment_likes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('comment_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('comments', sa.Column('parent_comment_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'comments', 'comments', ['parent_comment_id'], ['id'])
    op.add_column('posts', sa.Column('views_count', sa.Integer(), nullable=False))
    op.add_column('posts', sa.Column('tags', postgresql.ARRAY(sa.TEXT()), nullable=True))
    op.add_column('posts', sa.Column('trending_coefficient', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'trending_coefficient')
    op.drop_column('posts', 'tags')
    op.drop_column('posts', 'views_count')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'parent_comment_id')
    op.drop_table('comment_likes')
    op.drop_table('post_views')
    op.drop_table('post_likes')
    # ### end Alembic commands ###
